---
- name: Install or upgrade Newt client
  hosts: all
  become: true
  vars:
    version: "1.3.4"
    newt_url: "https://github.com/fosrl/newt/releases/download/{{version}}/newt_linux_amd64"
    newt_dest: "/usr/local/bin/newt"

  tasks:
    - name: Check if Newt binary exists
      stat:
        path: "{{ newt_dest }}"
      register: newt_binary

    - name: Get installed Newt version (if present)
      command: "{{ newt_dest }} --version"
      register: installed_version_raw
      when: newt_binary.stat.exists
      changed_when: false
      failed_when: false

    - name: Extract installed version number
      set_fact:
        installed_version_clean: "{{ installed_version_raw.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') }}"
      when: newt_binary.stat.exists

    - name: Decide if Newt needs updating
      set_fact:
        update_newt: "{{ (not newt_binary.stat.exists) or (installed_version_clean is not defined) or (installed_version_clean != version) }}"

    - name: Download Newt {{ version }} binary
      get_url:
        url: "{{ newt_url }}"
        dest: /tmp/newt
        mode: '0755'
      when: update_newt

    - name: Install or replace Newt binary
      copy:
        src: /tmp/newt
        dest: "{{ newt_dest }}"
        mode: '0755'
        force: yes
        remote_src: true
      when: update_newt

    - name: Verify Newt installation
      command: "{{ newt_dest }} --version"
      register: newt_ver
      changed_when: false

    - name: Show installed Newt version
      debug:
        msg: "Newt version installed: {{ newt_ver.stdout }}"
    
    - name: Restart newt.service if Newt was updated
      service:
        name: newt
        state: restarted
      when: update_newt
